server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bolsa-valores

  # === MongoDB ===
  data:
    mongodb:
      uri: link_mongo

  # === RabbitMQ ===
  rabbitmq:
    uri: link_cloudamqp
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2s

# === Logs ===
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.bolsas.monitoramento: DEBUG

# === Configurações customizadas (opcional) ===
bolsa:
  exchange: bolsa.exchange
  queue: cotacoes_bolsa
  routing-key: bolsa.cotacao.#
  apis:
    b3: "https://api.exemplo.com/b3"
