server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bolsa-valores

  # === MongoDB ===
  data:
    mongodb:
      uri: ""

  # === RabbitMQ ===
  rabbitmq:
    uri: ""
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2s

# === Logs ===
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.furb.bolsavalores: DEBUG
