server:
  port: 0
  servlet:
    context-path: /api

cluster:
  known-ports: "8081,8082,8083"

spring:
  application:
    name: bolsa-valores

  # === MongoDB ===
  data:
    mongodb:
      uri: "mongodb+srv://bchiamolera:Max060523@cluster0.85mqpdy.mongodb.net/bolsa-valores?retryWrites=true&w=majority"

  # === RabbitMQ ===
  rabbitmq:
    addresses: amqps://jackal.rmq.cloudamqp.com:5671
    username: tjonmisa
    password: Y7nP6069Ovl7R5vGHTiuK7IaIAHl2RJh
    virtual-host: tjonmisa
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        auto-startup: true
    connection-timeout: 5000
    dynamic: true


# === Logs ===
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.furb.bolsavalores: DEBUG
