server:
  port: 0
  servlet:
    context-path: /api

app:
  api: "brapi"
  ticker: "PETR4"

cluster:
  known-ports: "8081,8082,8083"

spring:
  application:
    name: bolsa-valores

  # === MongoDB ===
  data:
    mongodb:
      uri: "${MONGODB_URI_BOLSAVALORES}"

  # === RabbitMQ ===
  rabbitmq:
    addresses: "${RABBITMQ_ADDRESSES_BOLSAVALORES}"
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: auto


# === Logs ===
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.furb.bolsavalores: DEBUG
